### ISSUE TITLE
KeyError: 'Pavia'

### ISSUE THREAD

**Issue by lotfiGipsyKing** [hantek/deeplearn_hsi#3]
Traceback (most recent call last):
  File "pavia_SdA.py", line 38, in <module>
    img = scale_to_unit_interval(data['Pavia'].astype(theano.config.floatX))
KeyError: 'Pavia'

**Comment by hantek** [comment]
This is because the name of the key in your dictionary loaded by ``scipy.io()'' is different from that provided in the code.

I updated them in the new commit. Do a ``git pull origin master'' should solve this issue.
